#ifndef REVIEWRECORD_GLOBAL_H
#define REVIEWRECORD_GLOBAL_H

#include <QtGlobal>

#if defined(REVIEWRECORD_LIBRARY)
#  define REVIEWRECORDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REVIEWRECORDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REVIEWRECORD_GLOBAL_H
